name: Generar y desplegar Javadoc en GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy JavaDoc
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: gh-pages
          java-version: 17
          java-distribution: temurin
          target-folder: docs 
          project: gradle
          custom-command: cd app/src/main/java && javadoc --ignore-source-errors -protected -splitindex -d ../../../../docs eina.unizar.melodiaapp eina.unizar.melodiaapp.Modules && cd ../../../..
