name: Generar y desplegar Javadoc en GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Instalar JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Entrar en el directorio del código
      run: cd app/src/main/java

    - name: Generar Javadoc
      run: javadoc -protected -splitindex -d ../../../../docs eina.unizar.melodiaapp eina.unizar.melodiaapp.Modules

    - name: Desplegar en GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.ACCESS_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./docs
