name: Generar y desplegar Javadoc en GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Dar permisos de ejecución a gradlew
      run: chmod +x ./gradlew
      
    - name: Cambiar finales de línea
      run: sed -i 's/\r//' gradlew

    - name: Generar Javadoc
      run: ./gradlew generateJavadoc

    - name: Copiar archivos Javadoc
      run: |
        mkdir -p docs
        cp -R app/build/docs/javadoc/* docs/

    - name: Desplegar en GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.ACCESS_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./docs
